export const metadata = {
  title: 'Next Js Fundamentals',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
         style={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
        }}
      >
          <header 
            style={{
              padding: '1rem',
              background: 'lightblue',
              textAlign: 'center',

            }}
          >
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
            <p>{metadata.title}</p>
          </header>

          <main
            style={{
              flex: 1,
              textAlign: 'center',
            }}
          >
            {children}
          </main>

          <footer
            style={{
              background: 'ghostwhite',
              padding: '1rem',
              textAlign: 'center',
            }}
          >
              <p>Footer</p>
          </footer>

      </body>
    </html>
  )
}
