export const metadata = {
  title: 'NEXT JS Fundamentals',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
    >
      <body
         style={{
          minHeight: '100vh',
          display: 'flex',
          flexDirection: 'column',
          
          margin: 0,
          padding: 0,
        }}
      >
          <header 
            style={{
              padding: '1rem',
              background: 'lightblue',
              textAlign: 'center',

            }}
          >
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
            <p>Header Part</p>
          </header>

          <main
            style={{
              textAlign: 'center',
            }}
          >
            {children}
          </main>

          <footer
            style={{
              marginTop: 'auto',
              
              background: 'lightblue',
              textAlign: 'center',
              padding: '1rem',
            }}
          >
              <p>Footer Part</p>
          </footer>

      </body>
    </html>
  )
}
